version: "3.8"
services:
  redis:
    container_name: hompimpa-redis
    image: redislabs/rejson:latest
    # command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    # environment:
    #   - PASSWORD=${REDIS_PASSWORD}
    # networks:
    #   - hompimpa
    ports:
      - "6379:6379"

  # server:
  #   container_name: server-hompimpa
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${SERVER_PORT}:${SERVER_PORT}"
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     - DB_HOST=db
  #     - REDIS_HOST=redis
  #   networks:
  #     - shortener
  #   command: ["/app/main"]

networks:
  hompimpa:
    driver: bridge
