version: "3.8"
services:
  redis:
    container_name: hompimpa-redis
    image: redis:6.2.4-alpine
    restart: always
    networks:
      - hompimpa

  server:
    container_name: server-hompimpa
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - hompimpa
    command: ["/app/main"]

networks:
  hompimpa:
    driver: bridge
